2019-12-08 23:01:22.574450HTTPConnectionPool(host='221.215.38.232', port=8080): Max retries exceeded with url: /Qd_Admin/Login.aspx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x049613D0>, 'Connection to 221.215.38.232 timed out. (connect timeout=10)'))
2019-12-08 23:01:32.580086HTTPConnectionPool(host='120.220.4.9', port=80): Max retries exceeded with url: /webptframe/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x041D1B90>, 'Connection to 120.220.4.9 timed out. (connect timeout=10)'))
2019-12-08 23:02:21.798695HTTPSConnectionPool(host='219.157.119.13', port=443): Max retries exceeded with url: /html/login.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04E098D0>, 'Connection to 219.157.119.13 timed out. (connect timeout=10)'))
2019-12-08 23:02:22.237704HTTPConnectionPool(host='jdgc.lsgx.com.cn', port=80): Max retries exceeded with url: /e/master/login.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x010B1D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2019-12-08 23:03:37.638757HTTPConnectionPool(host='bx.liantuo.com', port=80): Max retries exceeded with url: /login.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04DD9E30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2019-12-08 23:04:22.630292HTTPConnectionPool(host='datamining.168p2p.com', port=80): Read timed out. (read timeout=10)
